name: Activity Box

on:
  schedule:
    - cron: '30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: JasonEtco/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: swimmy4days
          GIST_ID: ffe5100d4b9ebda468f4a3e61af8f6aa
